/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Primary – Blue
        "primary": "#2563EB",
        "primary-dark": "#1D4ED8",
        "primary-light": "#3B82F6",
        "primary-container": "#EFF6FF",
        "on-primary": "#ffffff",
        "on-primary-container": "#1E3A8A",
        // Secondary
        "secondary": "#475569",
        "secondary-container": "#F1F5F9",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#1E293B",
        // Tertiary
        "tertiary": "#0F766E",
        "tertiary-container": "#CCFBF1",
        "on-tertiary": "#ffffff",
        // Surface
        "surface": "#FAFAFA",
        "surface-dim": "#F1F5F9",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#F8FAFC",
        "surface-container": "#F1F5F9",
        "surface-container-high": "#E2E8F0",
        "surface-container-highest": "#CBD5E1",
        "surface-variant": "#F1F5F9",
        "surface-tint": "#2563EB",
        "on-surface": "#0F172A",
        "on-surface-variant": "#64748B",
        "on-background": "#0F172A",
        "background": "#F8FAFC",
        // Sidebar specific
        "sidebar": "#FFFFFF",
        "sidebar-border": "#E2E8F0",
        "sidebar-hover": "#F0F7FF",
        "sidebar-active": "#EFF6FF",
        "sidebar-active-border": "#2563EB",
        "sidebar-text": "#374151",
        "sidebar-text-muted": "#9CA3AF",
        // Outline
        "outline": "#E2E8F0",
        "outline-strong": "#CBD5E1",
        "outline-variant": "#F1F5F9",
        // Error
        "error": "#DC2626",
        "error-container": "#FEE2E2",
        "on-error": "#ffffff",
        "on-error-container": "#991B1B",
        // Semantic
        "success": "#16A34A",
        "success-container": "#DCFCE7",
        "warning": "#D97706",
        "warning-container": "#FEF3C7",
        "info": "#2563EB",
        "info-container": "#DBEAFE",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.375rem",
        "md": "0.5rem",
        "lg": "0.625rem",
        "xl": "0.875rem",
        "2xl": "1.125rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "space-xl": "1.5rem",
        "space-xs": "0.25rem",
        "space-md": "0.75rem",
        "margin": "1rem",
        "gutter": "1rem",
        "space-sm": "0.5rem",
        "space-lg": "1rem",
      },
      fontFamily: {
        "sans": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-sm": ["Inter", "ui-sans-serif"],
        "label-sm": ["Inter", "ui-sans-serif"],
        "body-lg": ["Inter", "ui-sans-serif"],
        "label-lg": ["Inter", "ui-sans-serif"],
        "headline-lg": ["Inter", "ui-sans-serif"],
        "label-md": ["Inter", "ui-sans-serif"],
        "body-sm": ["Inter", "ui-sans-serif"],
        "label-xs": ["Inter", "ui-sans-serif"],
        "body-md": ["Inter", "ui-sans-serif"],
        "headline-md": ["Inter", "ui-sans-serif"],
        "title-md": ["Inter", "ui-sans-serif"],
      },
      fontSize: {
        "headline-lg": ["22px", { "lineHeight": "30px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.005em", "fontWeight": "700" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "title-md":    ["15px", { "lineHeight": "22px", "fontWeight": "600" }],
        "label-lg":    ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "label-md":    ["13px", { "lineHeight": "18px", "fontWeight": "600" }],
        "label-sm":    ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "label-xs":    ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-lg":     ["15px", { "lineHeight": "22px", "fontWeight": "400" }],
        "body-md":     ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-sm":     ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
      },
      boxShadow: {
        "card": "0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.06)",
        "card-hover": "0 4px 12px -2px rgb(0 0 0 / 0.08), 0 2px 6px -2px rgb(0 0 0 / 0.06)",
        "modal": "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
        "sidebar": "1px 0 0 0 #E2E8F0",
        "sm": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "DEFAULT": "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
        "md": "0 4px 6px -1px rgb(0 0 0 / 0.07), 0 2px 4px -2px rgb(0 0 0 / 0.07)",
        "lg": "0 10px 15px -3px rgb(0 0 0 / 0.07), 0 4px 6px -4px rgb(0 0 0 / 0.05)",
        "xl": "0 20px 25px -5px rgb(0 0 0 / 0.08), 0 8px 10px -6px rgb(0 0 0 / 0.05)",
        "button": "0 1px 2px 0 rgb(37 99 235 / 0.3)",
      },
      animation: {
        "fade-in": "fadeIn 0.2s ease-out",
        "slide-in": "slideIn 0.25s ease-out",
        "slide-up": "slideUp 0.2s ease-out",
        "scale-in": "scaleIn 0.15s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideIn: {
          "0%": { opacity: "0", transform: "translateX(-8px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.96)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
    },
  },
  plugins: [],
}
