import { useMemo, useState } from 'react';

type Status='Chưa duyệt'|'Đã duyệt'|'Từ chối';
type Request={id:number;name:string;meta:string;type:string;oldValue:string;newValue:string;status:Status};
const initial:Request[]=[
 {id:1,name:'Lê Minh Quân',meta:'NV-0204 · Kỹ thuật',type:'Chuyển phòng ban',oldValue:'Phòng Kỹ thuật',newValue:'Phòng Sản phẩm',status:'Chưa duyệt'},
 {id:2,name:'Nguyễn Ngọc Mai',meta:'NV-0176 · Tài chính',type:'Thay đổi chức vụ',oldValue:'Chuyên viên',newValue:'Chuyên viên chính',status:'Chưa duyệt'},
 {id:3,name:'Phạm Gia Huy',meta:'NV-0113 · Vận hành',type:'Đổi quản lý trực tiếp',oldValue:'Đỗ Hải Nam',newValue:'Vũ Minh Đức',status:'Từ chối'},
 {id:4,name:'Trần Bảo Ngọc',meta:'NV-0089 · Marketing',type:'Thông tin cá nhân',oldValue:'SĐT 0903 *** 182',newValue:'SĐT 0988 *** 514',status:'Đã duyệt'},
 {id:5,name:'Đặng Hoàng Nam',meta:'NV-0321 · Vận hành',type:'Địa điểm làm việc',oldValue:'Văn phòng Hà Nội',newValue:'Chi nhánh TP.HCM',status:'Chưa duyệt'},
];
const tone=(s:Status)=>s==='Chưa duyệt'?'border-amber-200 bg-amber-50 text-amber-600':s==='Đã duyệt'?'border-emerald-200 bg-emerald-50 text-emerald-600':'border-rose-200 bg-rose-50 text-rose-600';

export default function InfoChangeApprovals(){
 const [rows,setRows]=useState(initial);const[query,setQuery]=useState('');const[status,setStatus]=useState('Tất cả trạng thái');const[type,setType]=useState('Tất cả loại thay đổi');
 const visible=useMemo(()=>rows.filter(r=>(status==='Tất cả trạng thái'||r.status===status)&&(type==='Tất cả loại thay đổi'||r.type===type)&&`${r.name} ${r.meta} ${r.type} ${r.oldValue} ${r.newValue}`.toLowerCase().includes(query.toLowerCase())),[rows,query,status,type]);
 const update=(id:number,next:Status)=>setRows(v=>v.map(r=>r.id===id?{...r,status:next}:r));
 return <div className="min-h-full space-y-6 bg-[#f7f9fc] p-6">
  <header><h1 className="mt-2 text-3xl font-bold text-slate-900">Duyệt thay đổi</h1></header>
  <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[[17,'Tổng số yêu cầu','tổng yêu cầu thay đổi đợt này','indigo'],[rows.filter(x=>x.status==='Chưa duyệt').length,'Chưa duyệt','hồ sơ đang chờ xét duyệt','amber'],[12,'Đã duyệt','đã chấp thuận và ghi nhận hiệu lực','emerald'],[2,'Từ chối','hồ sơ không đạt điều kiện','rose']].map(([v,l,s,c])=><div key={String(l)} className={`rounded-xl border-l-4 bg-white p-5 shadow-sm ${c==='amber'?'border-amber-400':c==='emerald'?'border-emerald-500':c==='rose'?'border-rose-500':'border-indigo-500'}`}><p className="text-sm text-slate-500">{l}</p><p className="mt-1 text-3xl font-bold">{v}</p><p className="mt-1 text-xs text-slate-400">{s}</p></div>)}</div>
  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm">
   <div className="flex items-start border-b px-5 py-4"><h2 className="font-bold">Yêu cầu thay đổi hồ sơ nhân sự</h2><span className="material-symbols-outlined ml-auto text-slate-400">expand_more</span></div>
   <div className="flex flex-wrap gap-3 border-b bg-slate-50/50 px-5 py-3"><input value={query} onChange={e=>setQuery(e.target.value)} className="form-input max-w-sm" placeholder="Tìm nhân viên, mã nhân sự, từ khóa..."/><select value={type} onChange={e=>setType(e.target.value)} className="form-input max-w-[190px]"><option>Tất cả loại thay đổi</option>{initial.map(x=><option key={x.type}>{x.type}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="form-input max-w-[160px]"><option>Tất cả trạng thái</option><option>Chưa duyệt</option><option>Đã duyệt</option><option>Từ chối</option></select><select className="form-input max-w-[150px]"><option>Tất cả thời gian</option></select></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Nhân viên','Loại thay đổi','Giá trị hiện tại','Giá trị đề xuất','Trạng thái','Thao tác'].map(x=><th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody className="divide-y">{visible.map(r=><tr key={r.id} className="text-sm"><td className="px-5 py-4"><p className="font-medium text-slate-800">{r.name}</p><p className="mt-1 text-xs text-slate-400">{r.meta}</p></td><td className="px-5 py-5 font-medium">{r.type}</td><td className="px-5 py-5 text-slate-400">{r.oldValue}</td><td className="px-5 py-5 font-semibold text-blue-900">{r.newValue}</td><td className="px-5 py-5"><span className={`rounded-full border px-3 py-1 text-xs ${tone(r.status)}`}>{r.status}</span></td><td className="px-5 py-5"><div className="flex justify-center gap-2">{r.status==='Chưa duyệt'?<><button aria-label="Từ chối" onClick={()=>update(r.id,'Từ chối')} className="flex h-8 w-8 items-center justify-center rounded-lg border border-rose-200 text-rose-500">×</button><button aria-label="Duyệt" onClick={()=>update(r.id,'Đã duyệt')} className="flex h-8 w-8 items-center justify-center rounded-lg border border-emerald-200 text-emerald-600">✓</button></>:r.status==='Từ chối'?<button className="flex h-8 w-8 items-center justify-center rounded-lg border border-rose-200 text-rose-500">ⓘ</button>:<><button disabled className="flex h-8 w-8 items-center justify-center rounded-lg border border-slate-200 text-slate-300">×</button><button className="flex h-8 w-8 items-center justify-center rounded-lg border border-emerald-200 text-emerald-600">✓</button></>}</div></td></tr>)}</tbody></table></div>
   <footer className="flex items-center justify-between border-t px-5 py-4 text-xs text-slate-500"><span>Hiển thị 1–{visible.length} trong tổng số 25 bản ghi</span><div className="flex gap-1"><button className="h-8 w-8 rounded border">‹</button>{[1,2,3,4,5].map(x=><button key={x} className={`h-8 w-8 rounded border ${x===1?'bg-blue-900 text-white':''}`}>{x}</button>)}<button className="h-8 w-8 rounded border">›</button></div></footer>
  </section>
 </div>
}
