import { useState } from 'react';
import { Link } from 'react-router-dom';

export default function Register(){
  const [step,setStep]=useState(1); const [done,setDone]=useState(false);
  const next=(e:React.FormEvent)=>{e.preventDefault(); if(step<3)setStep(step+1);else setDone(true)};
  return <main className="min-h-screen bg-slate-50">
    <header className="border-b bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4"><div className="flex items-center gap-3"><span className="material-symbols-outlined rounded-xl bg-blue-600 p-2 text-white">fingerprint</span><div><b className="block text-slate-900">ACS System</b><span className="text-xs text-slate-500">Chấm công & Nhân sự</span></div></div><Link to="/login" className="btn-secondary">Đăng nhập</Link></div></header>
    <div className="mx-auto max-w-3xl px-5 py-10">
      <div className="mb-7 text-center"><h1 className="text-2xl font-bold">Đăng ký tài khoản</h1><p className="mt-2 text-sm text-slate-500">Tạo hồ sơ để Admin xét duyệt quyền truy cập hệ thống</p></div>
      <div className="mb-8 flex items-center justify-center">{['Thông tin cá nhân','Thông tin tổ chức','Đăng ký FaceID'].map((x,i)=><div key={x} className="flex items-center"><div className="flex flex-col items-center"><span className={`flex h-9 w-9 items-center justify-center rounded-full text-sm font-bold ${step>i?'bg-blue-600 text-white':'border bg-white text-slate-400'}`}>{step>i+1?'✓':i+1}</span><span className={`mt-2 text-xs font-semibold ${step===i+1?'text-blue-600':'text-slate-400'}`}>{x}</span></div>{i<2&&<span className={`mx-4 mb-5 h-0.5 w-24 ${step>i+1?'bg-blue-600':'bg-slate-200'}`}/>}</div>)}</div>
      {done?<section className="rounded-2xl border bg-white p-10 text-center shadow-sm"><span className="material-symbols-outlined text-5xl text-emerald-500">task_alt</span><h2 className="mt-4 text-xl font-bold">Đã gửi hồ sơ đăng ký</h2><p className="mt-2 text-sm text-slate-500">Hồ sơ đang ở trạng thái Chờ duyệt. Kết quả sẽ được gửi qua email.</p><Link to="/login" className="btn-primary mt-6 inline-flex">Về trang đăng nhập</Link></section>:<form onSubmit={next} className="overflow-hidden rounded-2xl border bg-white shadow-sm"><header className="border-b px-7 py-5"><h2 className="font-bold">{step===1?'Thông tin cá nhân và CCCD':step===2?'Thiết lập tổ chức & công tác':'Đăng ký khuôn mặt FaceID'}</h2></header><div className="grid gap-4 p-7 sm:grid-cols-2">
        {step===1&&<><label className="sm:col-span-2"><span className="form-label">Họ và tên *</span><input required className="form-input" placeholder="Nguyễn Văn An"/></label><label><span className="form-label">Ngày sinh *</span><input required type="date" className="form-input"/></label><label><span className="form-label">Giới tính *</span><select className="form-input"><option>Nam</option><option>Nữ</option><option>Khác</option></select></label><label><span className="form-label">Số CCCD *</span><input required className="form-input"/></label><label><span className="form-label">Ngày cấp *</span><input required type="date" className="form-input"/></label><label className="sm:col-span-2"><span className="form-label">Email công việc *</span><input required type="email" className="form-input"/></label></>}
        {step===2&&<><label className="sm:col-span-2"><span className="form-label">Địa điểm làm việc *</span><select className="form-input"><option>Trụ sở chính ACS Hà Nội</option><option>Chi nhánh Hồ Chí Minh</option></select></label><label><span className="form-label">Phòng ban *</span><select className="form-input"><option>Phòng Công nghệ thông tin</option><option>Phòng Nhân sự</option></select></label><label><span className="form-label">Chức vụ *</span><select className="form-input"><option>Nhân viên</option><option>Chuyên viên</option></select></label><label className="sm:col-span-2"><span className="form-label">Quản lý trực tiếp</span><select className="form-input"><option>Lê Hoàng Dũng</option></select></label></>}
        {step===3&&<div className="sm:col-span-2"><div className="mx-auto flex aspect-video max-w-xl items-center justify-center rounded-2xl bg-slate-900"><div className="text-center text-white"><span className="material-symbols-outlined text-7xl text-blue-400">face</span><p className="mt-3 font-semibold">Đưa khuôn mặt vào khung hình</p><p className="text-xs text-slate-400">Giữ thẳng khuôn mặt và đảm bảo đủ ánh sáng</p></div></div><label className="mt-5 flex items-start gap-3 text-sm text-slate-600"><input required type="checkbox" className="mt-1"/>Tôi đồng ý sử dụng dữ liệu khuôn mặt cho mục đích chấm công và kiểm soát ra vào theo chính sách doanh nghiệp.</label></div>}
      </div><footer className="flex justify-between border-t bg-slate-50 px-7 py-4"><button type="button" onClick={()=>step===1?history.back():setStep(step-1)} className="btn-secondary">Quay lại</button><button className="btn-primary">{step===3?'Hoàn tất đăng ký':'Tiếp tục →'}</button></footer></form>}
    </div>
  </main>
}
